"""Project file locations, resolved from the repository root.

Anchoring every path here lets each script run from any working directory.

    data/raw/        inputs as received: the EPLAN export, recordings
    data/processed/  files generated by the pipeline and experiments
    data/decisions/  human-authored decisions; never regenerated
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

DATA = ROOT / "data"
RAW = DATA / "raw"
PROCESSED = DATA / "processed"
DECISIONS = DATA / "decisions"

SCHEMATIC_RAW = RAW / "schematic.json"
SCHEMATIC = PROCESSED / "schematic.cleaned.json"
DROPPED = PROCESSED / "dropped.csv"
WALKING_ORDER = PROCESSED / "walking_order.csv"
BANDS = DECISIONS / "bands.csv"

RUNS = ROOT / "runs"
